# Experiment configuration file
# Specify dataset paths, model settings, labeling options, and statistics parameters.

provider: openai # which provider to use, must match one in configs/providers/
model: gpt-4.1-2025-04-14 # which model to use, must match one in the chosen provider

data_dir: dataset
providers_dir: configs/providers

# input files
icl_demo_file: convo-qs-eris-labelled-train.xlsx
test_file: convo-qs-eris-test.xlsx

taxonomy_file: configs/taxonomy.yaml

# how many datapoints to be labeled in one batch
batch_size: 50

# where to find the prompts
prompts_root: prompts
prompts_register_in_opik: true

# labeling settings
label_subcategories: true
include_icl_demo: true
include_subcategory_in_icl_demo: true

# test set meeting group column (Run by a specific team's meeting, e.g., Team A, Team B, etc.)
group_col: Team

# Column mapping (ICL demo and test may come from different datasets)
# ICL demo set column names
icl_demo_question_col: Questions
icl_demo_category_col: A-General Type of Questions
icl_demo_subcategory_col: A-Specific Type of Questions

# test set column names
test_question_col: Questions
test_category_col: A-General Type of Questions
test_subcategory_col: A-Specific Type of Questions

# stat configuration
stats:
  seed: 42
  n_boot: 10000
  alpha: 0.05
  # display order of labels in the stats report
  labels_order:
    - LLQ
    - DRQ
    - GDQ
